### ISSUE TITLE
.whitesource configuration in place, but no issues generated.

### ISSUE THREAD

**Issue by alvin-c-shih** [finos/qPython#8]
The config is:
* https://github.com/finos/qPython/blob/main/.whitesource

@mcleo-d thinks that some issues against the project should have been generated by WhiteSource against the project (old dependencies, maybe).

Could someone verify that WhiteSource scanning is functioning?

Thanks!

**Comment by maoo** [comment]
@alvin-c-shih - now that you're using safety for CVE scanning, this issue could be closed right?

**Comment by alvin-c-shih** [comment]
Security scanning looks good.  Details here:
* https://github.com/finos/kdb/issues/79

Closing the ticket.  Thanks!
